[package]
name = "pettyscript"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
nom = "7.1.3"
nom-supreme = "0.8.0"
thiserror = "1.0.38"
macros = { path = "./macros" }
once_cell = "1.17.1"
hashbrown = "0.13.2"
